package qub;

public interface FakeUSPSClientTests
{
    static void test(TestRunner runner)
    {
        runner.testGroup(FakeUSPSClient.class, () ->
        {
            USPSClientTests.test(runner, (Test test) -> FakeUSPSClient.create()
                .addTrackInfo(TrackInfo.createText()
                    .setId("helloworld")
                    .setSummary("The Postal Service could not locate the tracking information for your request. Please verify your tracking number and try again later."))
                .addTrackInfo(TrackInfo.createText()
                    .setId("EJ958088694US")
                    .addError(Error.create()
                        .setNumber("-2147219283")
                        .setDescription("A status update is not yet available on your package. It will be available when the shipper provides an update or the package is delivered to USPS. Check back soon. Sign up for Informed Delivery&lt;SUP>&amp;reg;&lt;/SUP> to receive notifications for packages addressed to you.")
                        .addHelpFile()
                        .addHelpContext()))
                .addTrackInfo(TrackInfo.createText()
                    .setId("9405511899564158800673")
                    .setSummary("Your item was delivered to the front desk, reception area, or mail room at 6:42 pm on November 24, 2020 in ONTARIO, CA 91761.")
                    .addDetail("Arrived at Post Office, 11/24/2020, 10:18 am, ONTARIO, CA 91762")
                    .addDetail("Out for Delivery, 11/24/2020, 7:10 am, ONTARIO, CA 91764")
                    .addDetail("Arrived at USPS Facility, November 23, 2020, 12:46 pm, ONTARIO, CA 91761")
                    .addDetail("Departed USPS Regional Facility, 11/23/2020, 11:59 am, CITY OF INDUSTRY CA DISTRIBUTION CENTER")
                    .addDetail("Arrived at USPS Regional Facility, November 23, 2020, 6:01 am, CITY OF INDUSTRY CA DISTRIBUTION CENTER")
                    .addDetail("Departed USPS Facility, 11/22/2020, 4:07 am, KENT, WA 98035")
                    .addDetail("Arrived at USPS Origin Facility, 11/21/2020, 11:44 pm, KENT, WA 98035")
                    .addDetail("Departed Post Office, November 21, 2020, 5:56 pm, BOTHELL, WA 98011")
                    .addDetail("USPS picked up item, November 21, 2020, 5:03 pm, BOTHELL, WA 98011")
                    .addDetail("Shipping Label Created, USPS Awaiting Item, November 19, 2020, 8:19 am, ONTARIO, CA 91764"))
                .addTrackInfo(TrackInfo.createFields()
                    .setId("helloworld")
                    .addError(Error.create()
                        .setNumber("-2147219302")
                        .setDescription("The tracking number may be incorrect or the status update is not yet available. Please verify your tracking number and try again later.")
                        .addHelpFile()
                        .addHelpContext()))
                .addTrackInfo(TrackInfo.createFields()
                    .setId("EJ958088694US")
                    .addError(Error.create()
                        .setNumber("-2147219283")
                        .setDescription("A status update is not yet available on your package. It will be available when the shipper provides an update or the package is delivered to USPS. Check back soon. Sign up for Informed Delivery&lt;SUP>&amp;reg;&lt;/SUP> to receive notifications for packages addressed to you.")
                        .addHelpFile()
                        .addHelpContext()))
                .addTrackInfo(TrackInfoFields.create()
                    .setId("9405511899564158800673")
                    .addSummary(TrackSummary.createFields()
                        .setEventTime("6:42 pm")
                        .setEventDate("November 24, 2020")
                        .setEvent("Delivered, Front Desk/Reception/Mail Room")
                        .setEventCity("ONTARIO")
                        .setEventState("CA")
                        .setEventZipCode("91761")
                        .setEventCountry("")
                        .setFirmName("")
                        .setName("")
                        .setAuthorizedAgent("false")
                        .setDeliveryAttributeCode("05"))
                    .addDetail(TrackDetail.createFields()
                        .setEventTime("10:18 am")
                        .setEventDate("November 24, 2020")
                        .setEvent("Arrived at Post Office")
                        .setEventCity("ONTARIO")
                        .setEventState("CA")
                        .setEventZipCode("91762")
                        .setEventCountry("")
                        .setFirmName("")
                        .setName("")
                        .setAuthorizedAgent("false"))
                    .addDetail(TrackDetail.createFields()
                        .setEventTime("7:10 am")
                        .setEventDate("November 24, 2020")
                        .setEvent("Out for Delivery")
                        .setEventCity("ONTARIO")
                        .setEventState("CA")
                        .setEventZipCode("91764")
                        .setEventCountry("")
                        .setFirmName("")
                        .setName("")
                        .setAuthorizedAgent("false"))
                    .addDetail(TrackDetail.createFields()
                        .setEventTime("12:46 pm")
                        .setEventDate("November 23, 2020")
                        .setEvent("Arrived at USPS Facility")
                        .setEventCity("ONTARIO")
                        .setEventState("CA")
                        .setEventZipCode("91761")
                        .setEventCountry("")
                        .setFirmName("")
                        .setName("")
                        .setAuthorizedAgent("false"))
                    .addDetail(TrackDetail.createFields()
                        .setEventTime("11:59 am")
                        .setEventDate("November 23, 2020")
                        .setEvent("Departed USPS Regional Facility")
                        .setEventCity("CITY OF INDUSTRY CA DISTRIBUTION CENTER")
                        .setEventState("")
                        .setEventZipCode("")
                        .setEventCountry("")
                        .setFirmName("")
                        .setName("")
                        .setAuthorizedAgent("false"))
                    .addDetail(TrackDetail.createFields()
                        .setEventTime("6:01 am")
                        .setEventDate("November 23, 2020")
                        .setEvent("Arrived at USPS Regional Facility")
                        .setEventCity("CITY OF INDUSTRY CA DISTRIBUTION CENTER")
                        .setEventState("")
                        .setEventZipCode("")
                        .setEventCountry("")
                        .setFirmName("")
                        .setName("")
                        .setAuthorizedAgent("false"))
                    .addDetail(TrackDetail.createFields()
                        .setEventTime("4:07 am")
                        .setEventDate("November 22, 2020")
                        .setEvent("Departed USPS Facility")
                        .setEventCity("KENT")
                        .setEventState("WA")
                        .setEventZipCode("98035")
                        .setEventCountry("")
                        .setFirmName("")
                        .setName("")
                        .setAuthorizedAgent("false"))
                    .addDetail(TrackDetail.createFields()
                        .setEventTime("11:44 pm")
                        .setEventDate("November 21, 2020")
                        .setEvent("Arrived at USPS Origin Facility")
                        .setEventCity("KENT")
                        .setEventState("WA")
                        .setEventZipCode("98035")
                        .setEventCountry("")
                        .setFirmName("")
                        .setName("")
                        .setAuthorizedAgent("false"))
                    .addDetail(TrackDetail.createFields()
                        .setEventTime("5:56 pm")
                        .setEventDate("November 21, 2020")
                        .setEvent("Departed Post Office")
                        .setEventCity("BOTHELL")
                        .setEventState("WA")
                        .setEventZipCode("98011")
                        .setEventCountry("")
                        .setFirmName("")
                        .setName("")
                        .setAuthorizedAgent("false"))
                    .addDetail(TrackDetail.createFields()
                        .setEventTime("5:03 pm")
                        .setEventDate("November 21, 2020")
                        .setEvent("USPS picked up item")
                        .setEventCity("BOTHELL")
                        .setEventState("WA")
                        .setEventZipCode("98011")
                        .setEventCountry("")
                        .setFirmName("")
                        .setName("")
                        .setAuthorizedAgent("false"))
                    .addDetail(TrackDetail.createFields()
                        .setEventTime("8:19 am")
                        .setEventDate("November 19, 2020")
                        .setEvent("Shipping Label Created, USPS Awaiting Item")
                        .setEventCity("ONTARIO")
                        .setEventState("CA")
                        .setEventZipCode("91764")
                        .setEventCountry("")
                        .setFirmName("")
                        .setName("")
                        .setAuthorizedAgent("false")
                        .setDeliveryAttributeCode("33"))));

            runner.testGroup("trackText(TrackRequest)", () ->
            {
                runner.test("with not found track id", (Test test) ->
                {
                    final FakeUSPSClient uspsClient = FakeUSPSClient.create();
                    final TrackResponseText response = uspsClient.trackText(TrackRequest.create().addTrackId("hellothere")).await();
                    test.assertNotNull(response);
                    test.assertEqual(Iterable.create(), response.getErrors());
                    test.assertEqual(Iterable.create(), response.getTrackInfo());
                });
            });

            runner.testGroup("trackText(TrackRequest)", () ->
            {
                runner.test("with not found track id", (Test test) ->
                {
                    final FakeUSPSClient uspsClient = FakeUSPSClient.create();
                    final TrackResponseFields response = uspsClient.trackField(TrackFieldRequest.create().addTrackId("hellothere")).await();
                    test.assertNotNull(response);
                    test.assertEqual(Iterable.create(), response.getErrors());
                    test.assertEqual(Iterable.create(), response.getTrackInfo());
                });
            });
        });
    }
}
